# -*- coding: utf-8 -*-
"""Linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qr9FHcuPkyU8aDse-y_4lMJS1qkPZph4
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score

#read california_housing test
df = pd.read_csv('/content/sample_data/house_price_prediction_renamed.csv')
print(df)

x=df['Area'].values
y=df['Price'].values

plt.scatter(x,y)
plt.xlabel('Area')
plt.ylabel('Price')
plt.show()

reg=linear_model.LinearRegression()
reg=reg.fit(df[['Area']],df['Price'])
y_pred=reg.predict(df[['Area']])

#printing the coef , intercept
print(reg.coef_)
print(reg.intercept_)

df['Prediction_Price']=y_pred
print(df)

plt.scatter(df['Area'],df['Price'])
plt.plot(df['Area'],df['Prediction_Price'])
plt.xlabel('Area')
plt.ylabel('Price')
plt.show()

#calculating mean squre value
mse=mean_squared_error(df['Price'],df['Prediction_Price'])
print(mse)
rmse=np.sqrt(mse)
print(rmse)
r2_score=reg.score(df[['Area']],df['Price'])
print(r2_score)