# -*- coding: utf-8 -*-
"""Seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WEnhSCE4-OMfNFux3gtkjXXQu9E3LI4W
"""

import seaborn as sns
from sklearn.preprocessing import MinMaxScaler

data=sns.load_dataset('titanic')

type(data)

print(data.head(5))

#remove the same column
#data cleaning
data=data.drop(['sex','class','embarked','alive'],axis=1)
print(data)

print(data.isnull().sum())

data.shape

data=data.drop(['deck'],axis=1)

#in age adding medium if value is null
data['age']=data['age'].fillna(data['age'].mean())
print(data)

data=data.dropna()
print(data.isnull().sum())

print(data.head())

#converting into numeric
data['embark_town'].unique()

from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
data['embark_town']=LE.fit_transform(data['embark_town'])
data['who']=LE.fit_transform(data['who'])
print(data.head())

x=data.iloc[:,1:]
y=data.iloc[:,0]
print(x,y)

#normalising the values
MMS=MinMaxScaler()
x_nor=MMS.fit_transform(x)
print(x)

import pandas as pd
data=pd.DataFrame(x_nor)
print(data)

#model for logistic regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=17)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

model=LogisticRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
print(y_pred)

model.score(x_test,y_test)

#calculating f1 score
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

